name: shop_ease
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.3
  twitter_login: ^4.4.2
  provider: ^6.1.2
  intl: ^0.19.0
  http: ^1.2.2
  shared_preferences: ^2.3.2
  flutter_svg: ^2.0.10+1
  another_flushbar: ^1.12.30
  flutter_screenutil: ^5.9.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg_icons/
    - assets/fonts/
  fonts:
    - family: SFPRODISPLAY
      fonts:
        - asset: assets/fonts/SFPRODISPLAYREGULAR.OTF
        - asset: assets/fonts/SFPRODISPLAYBOLD.OTF
        - asset: assets/fonts/SFPRODISPLAYMEDIUM.OTF